### PR TITLE
Add notebook tours, icons

### LINKED ISSUE #26: JSON Tours in Notebook metadata
Hooray 3.1.0! Here's another direction we can go pretty quickly now that we have the schema in.

## Elevator pitch

Add another plugin, `notebook-tours`, which can find tours in user's notebook metadata, and pop a toast when a tour is found in a newly-opened notebook. Offer a notebook toolbar button (icon time!) which offers a list of tours saved in the notebook. Another optional plugin would add a tour sidebar with an edit mode, showing a nice UI for viewing/updating the schema instance.

## Motivation

In the general case, if a user builds an interesting, but complicated, notebook, it would act as a nice piece of annotation and documentation of how to use it if it offered a tour.

Concretely, over on https://github.com/jtpio/jupyterlite/pull/98 we're using the settings-based tours, and it works great. However, because each example notebook quacks a _little_ different than one might be used to, e.g. `import micropip; await micropip.install(...)`, and these would be nice to reflect a little more than pure narrative... also it's _slow_, and a tour would give the user something to look at while the cache warms up!

Having UI for building the schema would help the raw JSON5 experience, as quotes, newlines, etc. wouldn't be so rough.

## Design ideas

I'm imagining it makes the most sense for the the metadata to live in `#/metadata/jupyterlab-tour/` and just be the same structure as the user settings. Right now, it just has the `tours` key, and whatever else goes in settings might not make sense later, but it should still validate. 

`react-json-schema-form` (or slightly more packaged, but not as a standalone labextension, `jupyterlab-rjsf` which would directly support markdown #20) would be a quick win to reuse all the content from the settings schema to drive the UI, as it already has the basics covered like switches, dropdowns, colors, etc.

For the crucial building of CSS selector, on a few things, e.g. robotkernel, we've used [simmerjs](https://github.com/gmmorris/simmerjs) to solve based on a clicked DOM node. We can make an rjsf component that overloads specific parts of a schema that would provide a point-and-click tool to filling in the textbox.

## Alternative

In addition to notebook metadata, a MIME renderer would be another way to generate tours, and these could be discovered by a slightly deeper query of the notebook, and exposed in the same way... or just show a "start tour" button. This gets tricky, as we'd need to reserve a mime type, etc.

### PR DESCRIPTION
**Pull request by bollwyvl**
- fixes #26 (at least the show-a-tour part)
- [x] includes #28
- [x] adds some icons
- [x] unifies translation and sorting in the `tourManager`
- [x] use schema to validate metadata
- [x] figure out how to un-confuse `ts-jest` when using the `tsconfig.json` setup that allows for importing schema, etc.
- [ ] update some more things to be `IOptions` instead of ever-longer positional/optional args?
- [ ] add a `label` to the launch args to be able to find by human-readable name?
  - > this would allow for command-linker HTML, which would be nice 
- [ ] improve/replace the launch dialog
  - [ ] at a minimum, show the human-readable name
- [ ] add tours to launcher?
- [ ] add some client specificity awareness to tours
  - [ ] `notebookPage`?
- [ ] create a MIME renderer?
- [ ] avoid extra copy of `ajv`
- [ ] avoid duplicate assets in `$prefix/share` and `labextension`
- [ ] toast?
 
## screens
| what | it looks like |
|-|-|
| basic notebook ui |Screenshot from 2021-05-22 14-50-58
| icons in help | Screenshot from 2021-05-22 14-51-11
| icon in palette  | Screenshot from 2021-05-22 14-51-55
| icon in advanced settings | Screenshot from 2021-05-22 14-53-55
| icon when it's busted | Screenshot from 2021-05-22 16-59-14

### CODE REVIEW

**Comment by fcollonval** [comment]
@bollwyvl would you have time to look at the rebase?

**Comment by bollwyvl** [comment]
Yeah, meant to do that, but frankly don't remember what was
contentious/half done, so might take me a bit of looking.

**Comment by fcollonval** [comment]
> Yeah, meant to do that, but frankly don't remember what was contentious/half done, so might take me a bit of looking.

Thanks for getting back. Don't worry then. I'll move forward with this to get closer to a release; there are still two points I want to address before that.

**Comment by bollwyvl** [comment]
Looking now... i see you _already_ did the rebase. Rad! Looking now.

**Comment by bollwyvl** [comment]
Ran the setup locally and made some changes to the template-generated stuff which burned my eyes. 

I'll update the top comment with some thoughts on possible tasks to get this out the door...

**Comment by bollwyvl** [comment]
Looking at the list of stuff i added up top, it is again probably not worth blocking on this to get a major version alpha out that works with lab4/nb7, though some of the API changes would be breaking. 

Probably want a `3.x` branch (from ... a fairly long time ago), so we at least have the option of backporting stuff, time/need permitting.

**Pull request merged**
